{% set name = "celery-batches" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/51/12/30140c5961bd7b9a71d6e20f4ff0c93b6b96fee738c244b8118ca38276ee/celery_batches-0.10.tar.gz
  sha256: 2e898dab9bf0fed862107069066179278027fe1b87d4c4ee31a3b81713ed7dd3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=42.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - celery >=5.3

test:
  imports:
    - celery_batches
    
about:
  home: https://github.com/clokep/celery-batches
  summary: Experimental task class that buffers messages and processes them as a list.
  dev_url: https://github.com/clokep/celery-batches
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
